### PR TITLE
Adding ppolicy

### PR DESCRIPTION
**Pull request by jsdevel**

### CODE REVIEW

**Comment by jsdevel** [comment]
@dinkel thoughts on this PR?

**Comment by dinkel** [comment]
Hi @jsdevel,

Oops, somehow I missed this PR, sorry.  I will have a look at it in the next few days, but already thanks a lot for your contribution.

**Comment by jsdevel** [comment]
No worries!  Curious to know your thoughts on the addition.  I've been using `ppolicy` successfully with this fork.  I'd like to see it get merged though so I can unpublish my version!

**Comment by jsdevel** [comment]
Thanks @dinkel !

**Comment by dinkel** [comment]
Hi Joseph,

After reading into ppolicy and finally finding time I did merge your pull request. Thanks a lot for that!

I made some minor changes in the `entrypoint.sh` to keep a consistent coding style (although I do like your pipes in the sed arguments ;-)).

In the documentation in README.md I liked the bulletpoint style for the environment variable definitions, but I prefer "======" and "-----" underlining of headings. Did you have a special reason to change this? While learning about ppolicy I did move and rewrite parts of the ppolicy configuration instructions to hopefully be more clear.

I would appreciate if you had a look at the merged version and tell me if this fits your use.

Anyways thanks again for the contribution.

**Comment by jsdevel** [comment]
Your changes look fine.

**Pull request merged**
